version: 0
os: linux
files:
  - source: app/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop
      timeout: 300
      runas: root
AfterInstall:
  - location: scripts/start
    timeout: 300
    runas: root
